version: "3.8"

services:
  db:
    container_name: app-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "./db:/var/lib/mysql:rw"
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - app-db